In [93]:
import pandas as pd

query = """
SELECT *
FROM `Ancine.films_w1_w4`
"""

df_ancine = pd.read_gbq(
    query,
    project_id="benoit-project-488815"
)

df_ancine.head()

/var/folders/d5/qxxn879j4ld95f_cnf_97tw40000gp/T/ipykernel_17373/1913180801.py:8: FutureWarning:

read_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.read_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq

,title,release_date_clean,genre,production_countries,nationality,distributor,distributor_origin,screens_w1,screens_w2,screens_w3,...,revenue_w2,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct
0,Alguém Que Me Ame De Verdade,2009-01-09,Ficção,Estados Unidos,Estrangeira,Moviemobz,Distribuição Nacional,4,9,10,...,60276,45102,22217,10866.0,6697.0,4510.0,3174.0,125.000000,11.111111,-30.000000
1,Fundo Do Mar 3D,2009-01-16,Documentário,"Canadá, Estados Unidos",Estrangeira,Espaço Itaú De Cinema,Distribuição Nacional,1,1,1,...,191425,138335,45690,218375.0,191425.0,138335.0,45690.0,0.000000,0.000000,0.000000
2,Titãs - A Vida Até Parece Uma Festa,2009-01-16,Documentário,Brasil,Brasileira,Moviemobz,Distribuição Nacional,12,14,11,...,33407,21327,12818,4802.0,2386.0,1939.0,1602.0,16.666667,-21.428571,-27.272727
3,Novo Século Americano,2009-01-23,Documentário,Itália,Estrangeira,Moviemobz,Distribuição Nacional,3,3,1,...,4383,856,1028,2499.0,1461.0,856.0,1028.0,0.000000,-66.666667,0.000000
4,Rumba,2009-01-23,Ficção,França,Estrangeira,Filmes Do Estação,Distribuição Nacional,3,4,5,...,33329,14142,6200,17760.0,8332.0,2828.0,1550.0,33.333333,25.000000,-20.000000

In [94]:
df_ancine.isnull().mean().sort_values(ascending=False).head(20)

week_retention_w2_pct    0.000216
revenue_per_screen_w4    0.000216
revenue_per_screen_w1    0.000216
title                    0.000000
release_date_clean       0.000000
week_retention_w3_pct    0.000000
revenue_per_screen_w3    0.000000
revenue_per_screen_w2    0.000000
revenue_w4               0.000000
revenue_w3               0.000000
revenue_w2               0.000000
revenue_w1               0.000000
screens_w4               0.000000
screens_w3               0.000000
screens_w2               0.000000
screens_w1               0.000000
distributor_origin       0.000000
distributor              0.000000
nationality              0.000000
production_countries     0.000000
dtype: float64

In [95]:
df_ancine = df_ancine[
    (df_ancine["week_retention_w2_pct"].between(-100, 150)) &
    (df_ancine["revenue_per_screen_w1"].between(8000, 60000))
]

In [96]:
ancine_numeric = df_ancine.drop(["release_date_clean", "title", "genre", 'production_countries', "nationality", "distributor", "distributor_origin"], axis=1)
ancine_numeric.head()

,screens_w1,screens_w2,screens_w3,screens_w4,revenue_w1,revenue_w2,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct
0,4,9,10,7,43465,60276,45102,22217,10866.0,6697.0,4510.0,3174.0,125.000000,11.111111,-30.000000
4,3,4,5,4,53281,33329,14142,6200,17760.0,8332.0,2828.0,1550.0,33.333333,25.000000,-20.000000
9,6,6,13,6,62116,76329,35338,26404,10353.0,12722.0,2718.0,4401.0,0.000000,116.666667,-53.846154
14,25,20,15,10,200998,157068,53435,36127,8040.0,7853.0,3562.0,3613.0,-20.000000,-25.000000,-33.333333
16,137,180,193,194,3625911,2545810,2815754,1971689,26467.0,14143.0,14589.0,10163.0,31.386861,7.222222,0.518135

In [97]:
print(ancine_numeric.shape)
ancine_numeric = ancine_numeric.dropna()
print(ancine_numeric.shape)

(1217, 15)
(1217, 15)

In [98]:
ancine_numeric = ancine_numeric.dropna()

In [99]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
ancine_scaled = scaler.fit_transform(ancine_numeric)

ancine_scaled = pd.DataFrame(
    ancine_scaled,
    columns=ancine_numeric.columns,
    index=ancine_numeric.index
)
ancine_scaled.head()

,screens_w1,screens_w2,screens_w3,screens_w4,revenue_w1,revenue_w2,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct
0,-0.800802,-0.814082,-0.774447,-0.709375,-0.544224,-0.553519,-0.532430,-0.492871,-0.485712,-0.529815,-0.515993,-0.553756,4.558587,0.486590,-0.123305
4,-0.802680,-0.824714,-0.787121,-0.718835,-0.543485,-0.556675,-0.538197,-0.497511,0.628275,-0.239793,-0.887331,-1.003951,1.184375,0.739536,0.080595
9,-0.797046,-0.820461,-0.766842,-0.712528,-0.542820,-0.551639,-0.534248,-0.491658,-0.568606,0.538923,-0.911616,-0.213615,-0.042611,2.408977,-0.609529
14,-0.761362,-0.790691,-0.761773,-0.699915,-0.532366,-0.542185,-0.530877,-0.488841,-0.942359,-0.324760,-0.725284,-0.432059,-0.778803,-0.171069,-0.191272
16,-0.551013,-0.450455,-0.310574,-0.119709,-0.274551,-0.262471,-0.016310,0.071848,2.035221,0.790986,1.709165,1.383690,1.112726,0.415765,0.498961

In [100]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

kmeans_10_labels = KMeans(n_clusters=10, n_init=10)


kmeans_10_labels.fit(ancine_scaled)

# Add predictions to the original dataframe
ancine_scaled["kmeans_10_labels_pred"] = kmeans_10_labels.labels_

ancine_scaled.head()

,screens_w1,screens_w2,screens_w3,screens_w4,revenue_w1,revenue_w2,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct,kmeans_10_labels_pred
0,-0.800802,-0.814082,-0.774447,-0.709375,-0.544224,-0.553519,-0.532430,-0.492871,-0.485712,-0.529815,-0.515993,-0.553756,4.558587,0.486590,-0.123305,5
4,-0.802680,-0.824714,-0.787121,-0.718835,-0.543485,-0.556675,-0.538197,-0.497511,0.628275,-0.239793,-0.887331,-1.003951,1.184375,0.739536,0.080595,0
9,-0.797046,-0.820461,-0.766842,-0.712528,-0.542820,-0.551639,-0.534248,-0.491658,-0.568606,0.538923,-0.911616,-0.213615,-0.042611,2.408977,-0.609529,0
14,-0.761362,-0.790691,-0.761773,-0.699915,-0.532366,-0.542185,-0.530877,-0.488841,-0.942359,-0.324760,-0.725284,-0.432059,-0.778803,-0.171069,-0.191272,0
16,-0.551013,-0.450455,-0.310574,-0.119709,-0.274551,-0.262471,-0.016310,0.071848,2.035221,0.790986,1.709165,1.383690,1.112726,0.415765,0.498961,9

In [101]:
ancine_scaled.groupby("kmeans_10_labels_pred").count()

,screens_w1,screens_w2,screens_w3,screens_w4,revenue_w1,revenue_w2,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct
kmeans_10_labels_pred,,,,,,,,,,,,,,,
0,532,532,532,532,532,532,532,532,532,532,532,532,532,532,532
1,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
2,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
3,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74
4,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
5,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66
6,175,175,175,175,175,175,175,175,175,175,175,175,175,175,175
7,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
8,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
9,239,239,239,239,239,239,239,239,239,239,239,239,239,239,239

In [102]:
inertias = []
n_k = range(1, 11)

# for each number of centroids
for k in n_k:  
    model = KMeans(n_clusters=k, random_state=0, n_init=10)
    model.fit(ancine_scaled)
    inertias.append(model.inertia_)

#Graph
import plotly.express as px
fig = px.scatter(inertias)
fig.show()

In [103]:
ancine_scaled = ancine_scaled.drop(["kmeans_10_labels_pred"], axis=1)

In [104]:
kmeans_4_labels = KMeans(n_clusters=4, n_init=10)

kmeans_4_labels.fit(ancine_scaled)

# Add predictions to the original dataframe
df_ancine["label"] = kmeans_4_labels.labels_

df_ancine.head()

,title,release_date_clean,genre,production_countries,nationality,distributor,distributor_origin,screens_w1,screens_w2,screens_w3,...,revenue_w3,revenue_w4,revenue_per_screen_w1,revenue_per_screen_w2,revenue_per_screen_w3,revenue_per_screen_w4,week_retention_w2_pct,week_retention_w3_pct,week_retention_w4_pct,label
0,Alguém Que Me Ame De Verdade,2009-01-09,Ficção,Estados Unidos,Estrangeira,Moviemobz,Distribuição Nacional,4,9,10,...,45102,22217,10866.0,6697.0,4510.0,3174.0,125.000000,11.111111,-30.000000,3
4,Rumba,2009-01-23,Ficção,França,Estrangeira,Filmes Do Estação,Distribuição Nacional,3,4,5,...,14142,6200,17760.0,8332.0,2828.0,1550.0,33.333333,25.000000,-20.000000,3
9,O Visitante,2009-03-13,Ficção,Estados Unidos,Estrangeira,Moviemobz,Distribuição Nacional,6,6,13,...,35338,26404,10353.0,12722.0,2718.0,4401.0,0.000000,116.666667,-53.846154,3
14,Fiel - O Filme,2009-04-10,Documentário,Brasil,Brasileira,G7 Cinema,Distribuição Nacional,25,20,15,...,53435,36127,8040.0,7853.0,3562.0,3613.0,-20.000000,-25.000000,-33.333333,3
16,Divã,2009-04-17,Ficção,Brasil,Brasileira,Downtown/Riofilme,Distribuição Nacional,137,180,193,...,2815754,1971689,26467.0,14143.0,14589.0,10163.0,31.386861,7.222222,0.518135,1

In [105]:
fig_scaled = px.scatter_3d(df_ancine,
                           x="screens_w1",
                           y='revenue_per_screen_w1',
                           z='week_retention_w2_pct',
                           color="label",
                           width=500,
                           height=500)
fig_scaled.show()

In [106]:
releases_clusters = {}

for num_cluster in df_ancine["label"].unique():
    releases_clusters[num_cluster] = df_ancine[
        df_ancine["label"] == num_cluster
    ].sample(15)
    
releases_clusters

{3:                                      title release_date_clean         genre  \
 2982                             Megamente         2010-12-03      Animação
 3055                        Projeto Gemini         2019-10-10        Ficção
 4075                     O Abismo Prateado         2013-04-26        Ficção
 1459             Qualquer Gato Vira-Lata 2         2015-06-04        Ficção
 3216                         A Lenda De Oz         2014-10-09      Animação
 2118                               Pompeia         2014-02-21        Ficção
 2339                   Sonhos Em Movimento         2012-04-27  Documentário
 2141                 Simplesmente Acontece         2015-03-05        Ficção
 4030                      Feito Na América         2017-09-14        Ficção
 1857  Caminhando Com Dinossauros - O Filme         2014-01-17      Animação
 982                           O Último Ato         2015-04-02        Ficção
 4016                      A Garota No Trem         2016-10-27        Ficção
 1244        John Carter: Entre Dois Mundos         2012-03-09        Ficção
 1886            A Espiã Que Sabia De Menos         2015-06-04        Ficção
 4335                               A Força         2015-07-23        Ficção

                         production_countries  nationality     distributor  \
 2982                          Estados Unidos  Estrangeira       Paramount
 3055                   China, Estados Unidos  Estrangeira       Paramount
 4075                                  Brasil   Brasileira  Vitrine Filmes
 1459                                  Brasil   Brasileira  Downtown/Paris
 3216                   Estados Unidos, Índia  Estrangeira           Paris
 2118        Alemanha, Canadá, Estados Unidos  Estrangeira          Imagem
 2339                                Alemanha  Estrangeira       Imovision
 2141                          Estados Unidos  Estrangeira          Imagem
 4030                          Estados Unidos  Estrangeira       Universal
 1857  Austrália, Estados Unidos, Reino Unido  Estrangeira             Fox
 982                           Estados Unidos  Estrangeira      Califórnia
 4016                          Estados Unidos  Estrangeira       Universal
 1244                          Estados Unidos  Estrangeira          Disney
 1886                          Estados Unidos  Estrangeira             Fox
 4335                          Estados Unidos  Estrangeira          Warner

               distributor_origin  screens_w1  screens_w2  screens_w3  ...  \
 2982  Distribuição Internacional         457         421         388  ...
 3055  Distribuição Internacional         677         598         454  ...
 4075       Distribuição Nacional           5          12          14  ...
 1459       Distribuição Nacional         551         482         353  ...
 3216       Distribuição Nacional         460         402         194  ...
 2118       Distribuição Nacional         419         391         195  ...
 2339       Distribuição Nacional           3           3           2  ...
 2141       Distribuição Nacional         304         316         194  ...
 4030  Distribuição Internacional         553         551         300  ...
 1857  Distribuição Internacional         325         320         286  ...
 982        Distribuição Nacional          10          11           3  ...
 4016  Distribuição Internacional         310         319         344  ...
 1244  Distribuição Internacional         452         462         402  ...
 1886  Distribuição Internacional         305         305         101  ...
 4335  Distribuição Internacional         157         168          55  ...

       revenue_w3  revenue_w4  revenue_per_screen_w1  revenue_per_screen_w2  \
 2982     2278459     1948110                14086.0                 9933.0
 3055     1820105      402181                11020.0                 6106.0
 4075       14067       11860                10590.0                 1817.0
 1459     1638124      847134                 8697.0                 5605.0
 3216      299881      110212                 8763.0                 3236.0
 2118     1131840      214241                12267.0                13386.0
 2339        1868        3421                10298.0                 2319.0
 2141      765959      233198                10135.0                 5268.0
 4030     1248373      364489                 8340.0                 4519.0
 1857      935280      103015                13693.0                 6539.0
 982        11138        4339                10060.0                 5987.0
 4016     2475572      697960                15084.0                 8102.0
 1244     1790915      349421                12924.0                 9331.0
 1886      305361      105540                11205.0                 4388.0
 4335      155018       39855                10550.0                 4174.0

       revenue_per_screen_w3  revenue_per_screen_w4  week_retention_w2_pct  \
 2982                 5872.0                 5060.0              -7.877462
 3055                 4009.0                 2595.0             -11.669129
 4075                 1005.0                  988.0             140.000000
 1459                 4641.0                 4278.0             -12.522686
 3216                 1546.0                 1328.0             -12.608696
 2118                 5804.0                 4463.0              -6.682578
 2339                  934.0                 1140.0               0.000000
 2141                 3948.0                 2844.0               3.947368
 4030                 4161.0                 4050.0              -0.361664
 1857                 3270.0                 1908.0              -1.538462
 982                  3713.0                 2170.0              10.000000
 4016                 7196.0                 4179.0               2.903226
 1244                 4455.0                 1985.0               2.212389
 1886                 3023.0                 3015.0               0.000000
 4335                 2819.0                 2491.0               7.006369

       week_retention_w3_pct  week_retention_w4_pct  label
 2982              -7.838480              -0.773196      3
 3055             -24.080268             -65.859031      3
 4075              16.666667             -14.285714      3
 1459             -26.763485             -43.909348      3
 3216             -51.741294             -57.216495      3
 2118             -50.127877             -75.384615      3
 2339             -33.333333              50.000000      3
 2141             -38.607595             -57.731959      3
 4030             -45.553539             -70.000000      3
 1857             -10.625000             -81.118881      3
 982              -72.727273             -33.333333      3
 4016               7.836991             -51.453488      3
 1244             -12.987013             -56.218905      3
 1886             -66.885246             -65.346535      3
 4335             -67.261905             -70.909091      3

 [15 rows x 23 columns],
 1:                            title release_date_clean     genre  \
 3583       Tá Chovendo Hamburger         2009-10-02  Animação
 843              A Grande Beleza         2013-12-20    Ficção
 152   Até Que A Sorte Nos Separe         2012-10-05    Ficção
 3585               Bons Costumes         2009-10-23    Ficção
 2772                       Paris         2009-07-03    Ficção
 591                         1982         2022-06-02    Ficção
 4262                    A Origem         2010-08-06    Ficção
 2411             O Médico Alemão         2014-06-12    Ficção
 1823       Alvin E Os Esquilos 3         2012-01-06  Animação
 2294        Mademoiselle Chambon         2010-05-14    Ficção
 4328            Sniper Americano         2015-02-19    Ficção
 4260              Fúria De Titãs         2010-05-21    Ficção
 3642      007 – Operação Skyfall         2012-10-26    Ficção
 1092          O Jogo Da Imitação         2015-02-05    Ficção
 923               Os Mercenários         2010-08-13    Ficção

                      production_countries  nationality  \
 3583                       Estados Unidos  Estrangeira
 843                                Itália  Estrangeira
 152                                Brasil   Brasileira
 3585                               Canadá  Estrangeira
 2772                               França  Estrangeira
 591        França; Líbano; Noruega; Qatar  Estrangeira
 4262          Estados Unidos, Reino Unido  Estrangeira
 2411  Argentina, Espanha, França, Noruega  Estrangeira
 1823                       Estados Unidos  Estrangeira
 2294                               França  Estrangeira
 4328                       Estados Unidos  Estrangeira
 4260                       Estados Unidos  Estrangeira
 3642           Estados Unidos, Inglaterra  Estrangeira
 1092                          Reino Unido  Estrangeira
 923                        Estados Unidos  Estrangeira

                   distributor          distributor_origin  screens_w1  \
 3583                     Sony  Distribuição Internacional         182
 843         Alphaville Filmes       Distribuição Nacional          10
 152   Downtown/Paris/Riofilme       Distribuição Nacional         417
 3585                     Sony  Distribuição Internacional           3
 2772           Pandora Filmes       Distribuição Nacional           6
 591         Estúdio Escarlate       Distribuição Nacional           2
 4262                   Warner  Distribuição Internacional         313
 2411                Imovision       Distribuição Nacional           4
 1823                      Fox  Distribuição Internacional         539
 2294                Imovision       Distribuição Nacional           5
 4328                   Warner  Distribuição Internacional         203
 4260                   Warner  Distribuição Internacional         438
 3642                     Sony  Distribuição Internacional         537
 1092            Diamond Films       Distribuição Nacional         196
 923                Califórnia       Distribuição Nacional         177

       screens_w2  screens_w3  ...  revenue_w3  revenue_w4  \
 3583         180         178  ...     2035305     1498206
 843           10          10  ...      194860      151806
 152          425         417  ...     5091986     3399996
 3585           3           4  ...       23769        9702
 2772           6           6  ...       71952       43610
 591            1          12  ...       10127        2633
 4262         312         288  ...     2845236     1977217
 2411           3           2  ...       19873        4476
 1823         545         517  ...     6731055     4296936
 2294           1           2  ...       14725       44031
 4328         334         341  ...     3141017     1428512
 4260         434         435  ...     4980229     2929725
 3642         558         552  ...     5377279     3518510
 1092         164         145  ...     1246931      846556
 923          180         173  ...     1387906     1396946

       revenue_per_screen_w1  revenue_per_screen_w2  revenue_per_screen_w3  \
 3583                17023.0                25061.0                11434.0
 843                 16392.0                17014.0                19486.0
 152                 14215.0                19340.0                12211.0
 3585                20058.0                15336.0                 5942.0
 2772                19654.0                12420.0                11992.0
 591                 14650.0                16982.0                  844.0
 4262                16234.0                12015.0                 9879.0
 2411                10971.0                16508.0                 9937.0
 1823                28143.0                18212.0                13019.0
 2294                12436.0                67697.0                 7363.0
 4328                25419.0                14005.0                 9211.0
 4260                23829.0                19917.0                11449.0
 3642                17246.0                14963.0                 9741.0
 1092                10556.0                10986.0                 8600.0
 923                 19009.0                13217.0                 8023.0

       revenue_per_screen_w4  week_retention_w2_pct  week_retention_w3_pct  \
 3583                 7969.0              -1.098901              -1.111111
 843                 12651.0               0.000000               0.000000
 152                 10089.0               1.918465              -1.882353
 3585                 3234.0               0.000000              33.333333
 2772                 8722.0               0.000000               0.000000
 591                   439.0             -50.000000            1100.000000
 4262                 7518.0              -0.319489              -7.692308
 2411                 1492.0             -25.000000             -33.333333
 1823                 8841.0               1.113173              -5.137615
 2294                 7339.0             -80.000000             100.000000
 4328                 6675.0              64.532020               2.095808
 4260                 7128.0              -0.913242               0.230415
 3642                10053.0               3.910615              -1.075269
 1092                 7838.0             -16.326531             -11.585366
 923                  8169.0               1.694915              -3.888889

       week_retention_w4_pct  label
 3583               5.617978      1
 843               20.000000      1
 152              -19.184652      1
 3585             -25.000000      1
 2772             -16.666667      1
 591              -50.000000      1
 4262              -8.680556      1
 2411              50.000000      1
 1823              -5.996132      1
 2294             200.000000      1
 4328             -37.243402      1
 4260              -5.517241      1
 3642             -36.594203      1
 1092             -25.517241      1
 923               -1.156069      1

 [15 rows x 23 columns],
 2:                               title release_date_clean     genre  \
 3066              Top Gun: Maverick         2022-05-26    Ficção
 1830                A Era Do Gelo 4         2012-06-29  Animação
 1288  Capitão América: Guerra Civil         2016-04-28    Ficção
 4482          Velozes E Furiosos 10         2023-05-18    Ficção
 1918                          Logan         2017-03-02    Ficção
 1280    Vingadores: A Era De Ultron         2015-04-23    Ficção
 3984                        Minions         2015-06-25  Animação
 4449     Minions 2: A Origem De Gru         2022-06-30  Animação
 1290                Procurando Dory         2016-06-30  Animação
 1388             Mufasa: O Rei Leão         2024-12-19    Ficção
 4395                        Coringa         2019-10-03    Ficção
 1466   Os Dez Mandamentos - O Filme         2016-01-28    Ficção
 4487                         Barbie         2023-07-20    Ficção
 1905                       Deadpool         2016-02-11    Ficção
 1387                        Moana 2         2024-11-28  Animação

         production_countries  nationality     distributor  \
 3066   China; Estados Unidos  Estrangeira       Paramount
 1830          Estados Unidos  Estrangeira             Fox
 1288          Estados Unidos  Estrangeira          Disney
 4482          Estados Unidos  Estrangeira          Warner
 1918          Estados Unidos  Estrangeira             Fox
 1280          Estados Unidos  Estrangeira          Disney
 3984          Estados Unidos  Estrangeira       Universal
 4449          Estados Unidos  Estrangeira          Warner
 1290          Estados Unidos  Estrangeira          Disney
 1388          Estados Unidos  Estrangeira          Disney
 4395  Canadá, Estados Unidos  Estrangeira          Warner
 1466                  Brasil   Brasileira  Downtown/Paris
 4487          Estados Unidos  Estrangeira          Warner
 1905  Canadá, Estados Unidos  Estrangeira             Fox
 1387  Canadá; Estados Unidos  Estrangeira          Disney

               distributor_origin  screens_w1  screens_w2  screens_w3  ...  \
 3066  Distribuição Internacional        1702        1243        1287  ...
 1830  Distribuição Internacional        1010         900         893  ...
 1288  Distribuição Internacional        1635        1614        1599  ...
 4482    Distribuição Estrangeira        2277        1932        1355  ...
 1918  Distribuição Internacional        1211        1209         994  ...
 1280  Distribuição Internacional        1356        1272        1179  ...
 3984  Distribuição Internacional        1084        1049         964  ...
 4449  Distribuição Internacional        2105        1496        1397  ...
 1290  Distribuição Internacional        1276        1141        1019  ...
 1388    Distribuição Estrangeira        1942        1427        1163  ...
 4395  Distribuição Internacional        1726        1892        1525  ...
 1466       Distribuição Nacional        1127         959         727  ...
 4487    Distribuição Estrangeira        2521        2111        1612  ...
 1905  Distribuição Internacional         988        1002         932  ...
 1387    Distribuição Estrangeira        2110        2067        2119  ...

       revenue_w3  revenue_w4  revenue_per_screen_w1  revenue_per_screen_w2  \
 3066    16700200    14040314                12892.0                15256.0
 1830    19527131    12803830                23849.0                25335.0
 1288    23086885    10441886                37337.0                24011.0
 4482    17304091    14345511                26497.0                15287.0
 1918    14793914     7372587                30045.0                20048.0
 1280    21654884    13149371                37237.0                32037.0
 3984    24094214    15775823                31806.0                28086.0
 4449    21933662    17768577                12235.0                15384.0
 1290    19128702    13557644                31087.0                24198.0
 1388    19943826    14381641                13933.0                15162.0
 4395    24717937    16593837                25728.0                21613.0
 1466    11901517    10525617                29414.0                18682.0
 4487    20930347     8818112                48034.0                23280.0
 1905    11730392     7504960                34569.0                21416.0
 1387    26553458    12404683                30272.0                21602.0

       revenue_per_screen_w3  revenue_per_screen_w4  week_retention_w2_pct  \
 3066                12976.0                12988.0             -26.968273
 1830                21867.0                16290.0             -10.891089
 1288                14438.0                 9152.0              -1.284404
 4482                12771.0                12606.0             -15.151515
 1918                14883.0                10939.0              -0.165153
 1280                18367.0                14216.0              -6.194690
 3984                24994.0                19239.0              -3.228782
 4449                15701.0                12566.0             -28.931116
 1290                18772.0                15337.0             -10.579937
 1388                17149.0                13710.0             -26.519053
 4395                16208.0                11811.0               9.617613
 1466                16371.0                14185.0             -14.906832
 4487                12984.0                 6317.0             -16.263388
 1905                12586.0                10309.0               1.417004
 1387                12531.0                 8656.0              -2.037915

       week_retention_w3_pct  week_retention_w4_pct  label
 3066               3.539823             -16.006216      2
 1830              -0.777778             -11.982083      2
 1288              -0.929368             -28.642902      2
 4482             -29.865424             -16.014760      2

In [107]:
df_ancine.to_csv(
    "ancine_clusters.csv",
    index=False
)

In [110]:
df_plot = df_ancine

fig = px.scatter(
    df_plot,
    x="screens_w1",
    y="week_retention_w2_pct",
    size="revenue_per_screen_w1",
    color="label",
    hover_name="title",
    hover_data=[
        "distributor",
        "screens_w1",
        "revenue_per_screen_w1",
        "week_retention_w2_pct"
    ],
    size_max=15,
    height=600,
    width=1200,
    labels={
        "screens_w1": "Screens W1",
        "week_retention_w2_pct": "Screen retention W2 (%)",
        "revenue_per_screen_w1": "revenue_per_screen_w1",
        "category": "Cluster"
    },
    title="Brazil Releases - 4 categories"
)

fig.show()